### ISSUE TITLE
MayBe support more i2v models？

### ISSUE THREAD

**Issue by philipwan** [AdaCache-DiT/AdaCache#2]
Can AdaCache support 3D model except 2D + 1D. （open-sora-plan v1.2 or CogVideoX）
 How will the strategy be different?

**Comment by AdaCache-DiT** [comment]
Thanks for your interest in our work. We will include support to more models in the future. 

The overall strategy remains unchanged irrespective of 2+1D or 3D attention. We recently implemented on baseline CogVideoX and observed competitive speedups. The main functionality of AdaCache is in the forward pass of the baseline DiT, and [this](https://github.com/AdaCache-DiT/AdaCache/blob/2c6d3ca0320afd1f3ac41ac52673c79c8f6e00a4/opensora_base/opensora/models/stdit/stdit3.py#L185-L340) can be a reference when implementing on a new baseline.

**Comment by philipwan** [comment]
> Thanks for your interest in our work. We will include support to more models in the future.
> 
> The overall strategy remains unchanged irrespective of 2+1D or 3D attention. We recently implemented on baseline CogVideoX and observed competitive speedups. The main functionality of AdaCache is in the forward pass of the baseline DiT, and [this](https://github.com/AdaCache-DiT/AdaCache/blob/2c6d3ca0320afd1f3ac41ac52673c79c8f6e00a4/opensora_base/opensora/models/stdit/stdit3.py#L185-L340) can be a reference when implementing on a new baseline.

Thank you for your reply, I look forward to your expansion into new models.
