### ISSUE TITLE
关于 't-attn' 's-attn' 'ca-mlp' 选择

### ISSUE THREAD

**Issue by 1145284121** [AdaCache-DiT/AdaCache#3]
感谢开源，有一点关于配置的疑惑：现在的默认配置我理解是以blk_idx==13的‘s-attn' 的信息计算cache_rate，代表当前step全部的SA和TA，如果使用 't-attn' 's-attn' 'ca-mlp' 的差异求一个加权结果是不是会更合理，您有尝试过吗

**Comment by AdaCache-DiT** [comment]
Thank you for your interest in our work.

In our experiments, we observed that computing the cache-metric on either TA, SA, CA, or MLP residuals is not too different from eachother, but TA gives better quality-latency trade-offs in OpenSora (see ablation Table 3e in the paper). Computing the cache-metric at the middle of the DiT (blk_id = 13) was sufficient (see ablation Table 3d in the paper) in our experiments. We agrree that averaging this metric computed across all layers can be more reasonable, but it also introduces more latency overheads.
