### ISSUE TITLE
Why attn and mlp are cached separately？

### ISSUE THREAD

**Issue by sywang0111** [AdaCache-DiT/AdaCache#4]
https://github.com/AdaCache-DiT/AdaCache/blob/2c6d3ca0320afd1f3ac41ac52673c79c8f6e00a4/opensora_base/opensora/models/stdit/stdit3.py#L210-L221
It seems that attn_active and mlp_active are always both True or False.
If they are False, then:
`
x = x + attn_cache;
x = x + mlp_cache;
`
Maybe we can only cache only one `residual = attn_cache + mlp_cache`. so, `x = x + residual`.
Is there anything wrong with the above?
Thank you for your work and look forward your replying.

**Comment by AdaCache-DiT** [comment]
Thanks for your interest in our work.

This is a good question. In the formulation of AdaCache, we wanted to have more-flexibility (i.e., unique cache-schedules for each DiT-block, and even for each ATTN and MLP layer). However, in our experiments we find this to be unstable. Hence, we decide on using a common cache-shedule for all DiT blocks, shared by ATTN and MLP layers (hence, both are always either True or False). 

We can't keep all cached representations in a single buffer. We need to update `x = x + self.st_attn_cache` before we move on to CA and MLP (see [here](https://github.com/AdaCache-DiT/AdaCache/blob/2c6d3ca0320afd1f3ac41ac52673c79c8f6e00a4/opensora_base/opensora/models/stdit/stdit3.py#L272-L277)). But, we can afford to combine CA and MLP cache values (see [here](https://github.com/AdaCache-DiT/AdaCache/blob/2c6d3ca0320afd1f3ac41ac52673c79c8f6e00a4/opensora_base/opensora/models/stdit/stdit3.py#L299C13-L299C48)). So, we have one cache buffer to keep track of SA/TA and another to keep track of CA+MLP.
